name: Build

on:
  push:
    branches:
      - '*/*'
      - '*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 14.16
        uses: actions/setup-node@v1
        with:
          node-version: 14.16
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Save build
        uses: actions/upload-artifact@v1
        with:
          name: build
          path: ./dist
